# Site settings
title:       kid-cavaquinho.tostring()
email:       'joao[dot]antao[at]gmail[dot]com'
description: ''
baseurl:     '' 
url:         'https://kid-cavaquinho.github.io/'
github:      'https://github.com/kid-cavaquinho/'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext